In [1]:
import numpy as np
import mord as m

### Balanced 

In [13]:
X = np.array([[1]])
y = np.array([1])

# add 10x [1] --> [1] 
for i in range(10):
    new_elem_x = np.array([[1]])
    X = np.concatenate([X, new_elem_x])
    new_elem_y = np.array([1])
    y = np.concatenate([y, new_elem_y])

# add 10x [2] --> [2] 
for i in range(10):
    new_elem_x = np.array([[2]])
    X = np.concatenate([X, new_elem_x])
    new_elem_y = np.array([2])
    y = np.concatenate([y, new_elem_y])

X, y

(array([[1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2]]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]))

In [28]:
c = m.LogisticIT() #Default parameters: alpha=1.0, verbose=0, maxiter=10000
c.fit(X, y)
print c.predict(np.array([[1], [2]]))
print c.coef_, c.theta_

[1 2]
[ 2.41393604] [ 3.68281783]


### Imbalanced

In [23]:
X_im = np.array([[1]])
y_im = np.array([1])

# add 2x [1] --> [1] 
for i in range(2):
    new_elem_x = np.array([[1]])
    X_im = np.concatenate([X_im, new_elem_x])
    new_elem_y = np.array([1])
    y_im = np.concatenate([y_im, new_elem_y])

# add 18x [2] --> [2] 
for i in range(18):
    new_elem_x = np.array([[2]])
    X_im = np.concatenate([X_im, new_elem_x])
    new_elem_y = np.array([2])
    y_im = np.concatenate([y_im, new_elem_y])

X_im, y_im

(array([[1],
        [1],
        [1],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2]]),
 array([1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]))

In [27]:
c_im = m.LogisticIT() #Default parameters: alpha=1.0, verbose=0, maxiter=10000
c_im.fit(X_im, y_im)
print c_im.predict(np.array([[1], [2]]))
print c_im.coef_, c_im.theta_

[2 2]
[ 1.7972587] [ 1.39559951]


### Now fit via the All-Threshold method instead of Immediate Threshold

In [32]:
c_AT = m.LogisticAT() #Default parameters: alpha=1.0, verbose=0, maxiter=10000
c_AT.fit(X_im, y_im)
print c_AT.predict(np.array([[1], [2]]))
print c_AT.coef_, c_im.theta_

[2 2]
[ 1.7972587] [ 1.39559951]
